name: Alerta ntfy

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Enviar notificaci贸n a ntfy
        run: |
          curl -s -X POST \
            -H "Title: Notificaci贸n DevOps ITLA" \
            -H "Content-Type: text/plain" \
            --data-binary $'Se subi贸 nuevo c贸digo a la rama main del repo: ${{ github.repository }}' \
            https://ntfy.sh/devops-itla
